# Copyright 2018 Google LLC
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     https://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Clean up branch name so it can be used for tagging and namespace
# e.g. a common branch format may be feature/add-something.  The below
# will update that to feature-add-something
substitutions:
    _BRANCH_NAME_SANITIZED: "${BRANCH_NAME/[\\/_]/-}"

steps:

### Build

  - id: 'build'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
          docker build -t gcr.io/$PROJECT_ID/gceme:${_BRANCH_NAME_SANITIZED}-${SHORT_SHA} .



### Test


### Publish
  - id: 'publish'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
          docker push gcr.io/$PROJECT_ID/gceme:${_BRANCH_NAME_SANITIZED}-${SHORT_SHA}



### Deploy
  - id: 'deploy'
    name: 'gcr.io/cloud-builders/gcloud'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}'
      - 'KUBECONFIG=/kube/config'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
          CLUSTER=$$(gcloud config get-value container/cluster)
          PROJECT=$$(gcloud config get-value core/project)
          ZONE=$$(gcloud config get-value compute/zone)
          
          gcloud container clusters get-credentials "$${CLUSTER}" \
            --project "$${PROJECT}" \
            --zone "$${ZONE}"  


          
          

          sed -i 's|gcr.io/cloud-solutions-images/gceme:.*|gcr.io/$PROJECT_ID/gceme:${_BRANCH_NAME_SANITIZED}-${SHORT_SHA}|' ./kubernetes/deployments/dev/*.yaml
          
          # Let's validate our updates
          cat ./kubernetes/deployments/dev/*.yaml


          kubectl get ns ${_BRANCH_NAME_SANITIZED} || kubectl create ns ${_BRANCH_NAME_SANITIZED}
          kubectl apply --namespace ${_BRANCH_NAME_SANITIZED} --recursive -f kubernetes/deployments/dev
          kubectl apply --namespace ${_BRANCH_NAME_SANITIZED} --recursive -f kubernetes/services


